name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
      - run: yarn install --frozen-lockfile 
      - name: Run build
        run: bundle exec rails db:prepare               
      - run: bundle exec rails assets:precompile          
      - name: Run tests
        run: bundle exec rails test
      - name: Run linters
        run: bundle exec standardrb